/// <reference types="react-scripts" />

declare module "Models" {
  // Generated by https://quicktype.io

  export interface Crypto {
    status: string;
    data: Data;
  }

  export interface Data {
    stats: Stats;
    coins: Coin[];
  }

  export interface Coin {
    uuid: string;
    symbol: string;
    name: string;
    color: null | string;
    iconUrl: string;
    marketCap: string;
    price: string;
    listedAt: number;
    tier: number;
    change: string;
    rank: number;
    sparkline: string[];
    lowVolume: boolean;
    coinrankingUrl: string;
    "24hVolume": string;
    btcPrice: string;
  }

  export interface Stats {
    total: number;
    totalCoins: number;
    totalMarkets: number;
    totalExchanges: number;
    totalMarketCap: string;
    total24hVolume: string;
  }
  // Generated by https://quicktype.io

  export interface NewsModel {
    _type: string;
    webSearchUrl: string;
    value: Value[];
  }

  export interface Value {
    _type: ValueType;
    name: string;
    url: string;
    image?: ValueImage;
    description: string;
    provider: Provider[];
    datePublished: string;
  }

  export enum ValueType {
    NewsArticle = "NewsArticle",
  }

  export interface ValueImage {
    _type: ImageType;
    thumbnail: PurpleThumbnail;
    isLicensed: boolean;
  }

  export enum ImageType {
    ImageObject = "ImageObject",
  }

  export interface PurpleThumbnail {
    _type: ImageType;
    contentUrl: string;
    width: number;
    height: number;
  }

  export interface Provider {
    _type: ProviderType;
    name: string;
    image?: ProviderImage;
  }

  export enum ProviderType {
    Organization = "Organization",
  }

  export interface ProviderImage {
    _type: ImageType;
    thumbnail: FluffyThumbnail;
  }

  export interface FluffyThumbnail {
    _type: ImageType;
    contentUrl: string;
  }
  // Generated by https://quicktype.io

  export interface CoinDetail {
    status: string;
    data: Data;
  }

  export interface Data {
    coin: Coin;
  }

  export interface Coin {
    uuid: string;
    symbol: string;
    name: string;
    description: string;
    color: string;
    iconUrl: string;
    websiteUrl: string;
    links: Link[];
    supply: Supply;
    numberOfMarkets: number;
    numberOfExchanges: number;
    "24hVolume": string;
    marketCap: string;
    fullyDilutedMarketCap: string;
    price: string;
    btcPrice: string;
    priceAt: number;
    change: string;
    rank: number;
    sparkline: string[];
    allTimeHigh: AllTimeHigh;
    coinrankingUrl: string;
    tier: number;
    lowVolume: boolean;
    listedAt: number;
    hasContent: boolean;
    notices: null;
    tags: string[];
  }

  export interface AllTimeHigh {
    price: string;
    timestamp: number;
  }

  export interface Link {
    name: string;
    type: string;
    url: string;
  }

  export interface Supply {
    confirmed: boolean;
    supplyAt: number;
    max: string;
    total: string;
    circulating: string;
  }
}
